USE Portal;

CREATE TABLE User (
userID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
admin BIT NOT NULL DEFAULT 0,
username VARCHAR(20) NOT NULL UNIQUE,
password CHAR(32) NOT NULL,
description TEXT,
creationDate DATETIME NOT NULL,
modifiedDate DATETIME,
createdBy INTEGER,
lastModifiedBy INTEGER,
FOREIGN KEY(createdBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(lastModifiedBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT
) Engine=InnoDB;

CREATE TABLE Query (
queryID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
judulQuery VARCHAR(50) NOT NULL UNIQUE,
isiQuery TEXT NOT NULL,
databaseName VARCHAR(30) NOT NULL,
notes TEXT NOT NULL,
creationDate DATETIME NOT NULL,
modifiedDate DATETIME,
notesModifiedDate DATETIME,
createdBy INTEGER NOT NULL,
lastModifiedBy INTEGER,
lastNotesEditor INTEGER,
FOREIGN KEY(createdBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(lastModifiedBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(lastNotesEditor) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT
) Engine=InnoDB;

CREATE TABLE Connection (
connectionID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
serverName VARCHAR(20) NOT NULL,
IPAddress CHAR(15) NOT NULL,
username VARCHAR(20) NOT NULL,
password CHAR(32) NOT NULL,
description TEXT,
creationDate DATETIME NOT NULL,
modifiedDate DATETIME,
createdBy INTEGER NOT NULL,
lastModifiedBy INTEGER,
FOREIGN KEY(createdBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(lastModifiedBy) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT
) Engine=InnoDB;

CREATE TABLE User_Connection (
userID INTEGER NOT NULL,
connectionID INTEGER NOT NULL,
PRIMARY KEY(userID, connectionID), 
FOREIGN KEY(userID) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(connectionID) REFERENCES Connection(connectionID) ON UPDATE CASCADE ON DELETE RESTRICT
) Engine = InnoDB;

CREATE TABLE User_Query (
userID INTEGER NOT NULL,
queryID INTEGER NOT NULL,
PRIMARY KEY(userID, queryID), 
FOREIGN KEY(userID) REFERENCES User(userID) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(queryID) REFERENCES Query(queryID) ON UPDATE CASCADE ON DELETE RESTRICT
) Engine = InnoDB;